---
yandex:
  hosts:
    docker:
      ansible_host: 130.193.36.134
    web:
      ansible_host: 130.193.36.134
    app:
      ansible_host: 130.193.36.134
    db:
      ansible_host: 130.193.36.134
    proxy:
      ansible_host: 130.193.36.134
