---
yandex:
  hosts:
    docker_install:
      ansible_user: ansible
      ansible_port: 22
      ansible_host:
        - api.polzemli.ru
        - student.polzemli.ru
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    docker_compose:
      ansible_user: ansible
      ansible_port: 22
        - api.polzemli.ru
        - student.polzemli.ru
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    app:
      ansible_user: ansible
      ansible_port: 22
      ansible_host: api.polzemli.ru
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    db:
      ansible_user: ansible
      ansible_port: 222
      ansible_host: 8.9.10.11
      ansible_ssh_private_key_file: ~/.ssh/id_ed25519
