---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: debian:11
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  yamllint .
  ansible-lint .
