---
- name: Docker compose | copy template docker-compose.yml
  ansible.builtin.template:
    src: templates/docker-compose.j2
    dest: /home/{{ ansible_ssh_user }}/docker-compose.yml
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0644'

- name: Docker compose | copy template .env
  ansible.builtin.template:
    src: templates/env.j2
    dest: /home/{{ ansible_ssh_user }}/.env
    owner: '{{ ansible_ssh_user }}'
    group: '{{ ansible_ssh_user }}'
    mode: '0644'

- name: Docker compose | up -d
  ansible.builtin.command: docker compose -f docker-compose.yml up -d
  changed_when: false
