galaxy_info:
  author: Group
  namespace: ansible
  description: install docker
  company: Other
  license: BSD-3-Clause

  min_ansible_version: '2.1'
  platforms:
    - name: Debian
      versions:
      - bullseye

    - name: Ubuntu
      versions:
        - jammy

  galaxy_tags: []
dependencies: []
