---
- name: Docker | uninstall old versions
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    update_cache: true

- name: Docker | update the apt package index and install packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: true

- name: Docker | make keyrings dir
  ansible.builtin.file:
    path: /etc/apt/keyrings
    mode: '0755'
    state: directory
    owner: root

- name: Docker | add Dockers official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: /etc/apt/keyrings/docker.gpg
    state: present

- name: Docker | add apt source
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable'
    state: present

- name: Docker | to install the latest version
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: true

- name: Docker | start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Docker | add current user to the user's groups docker
  ansible.builtin.user:
    name: '{{ ansible_ssh_user }}'
    shell: /bin/bash
    groups: docker
    append: true

- name: Docker | debug info
  ansible.builtin.debug:
    msg: user "{{ ansible_ssh_user }}" add to group Docker
